[package]
name = "tun_nat"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.74"
sysconfig = { path = "../sysconfig" }
parking_lot = "0.11.0"
bitvec = "0.17.4"
smoltcp = { version = "0.6.0", default-features = false, features = ["proto-ipv6", "proto-ipv4", "std"] }
