[workspace]
members = [
    "seeker",
    "dnsserver",
    "ssclient",
    "sysconfig",
    "config",
    "crypto",
    "hermesdns",
    "socks5_client",
    "tun_nat",
    "http_proxy_client",
    "tcp_connection",
]

[profile.release]
lto = "fat"
codegen-units = 1
incremental = false
opt-level = "z"
