verbose: false
dns_start_ip: 11.0.0.10
# dns_servers:  # dns 服务器列表，如果不设置，会自动从系统获取
#   - 223.5.5.5:53
#   - 114.114.114.114:53
#   - tcp://114.114.114.114:53
dns_timeout: 1s
tun_bypass_direct: true  # 直连的域名直接返回真实IP，不走tun
tun_name: utun4
tun_ip: 11.0.0.1
tun_cidr: 11.0.0.0/16
dns_listen: 0.0.0.0:53
gateway_mode: true
probe_timeout: 200ms
ping_timeout: 2s
connect_timeout: 2s
read_timeout: 300s
write_timeout: 300s
max_connect_errors: 2
geo_ip: path/to/geoip.mmdb # geoip 数据库路径，如果使用相对路径，相对于可执行文件的路径。默认会搜索可执行文件同级目录下的 geoip.mmdb 文件
ping_urls:
  - host: www.facebook.com
    port: 80
    path: /
  - host: www.youtube.com
    port: 80
    path: /
  - host: twitter.com
    port: 80
    path: /

remote_config_urls:  # ss 订阅地址，启动时自动拉群配置，并将配置的服务器地址自动加入服务器列表
  - https://addr-to-ss-subscribe-url.com

servers:
  - name: a
    addr: 127.0.0.1:1087  # 替换成 http 代理的地址
    username:
    password:
    protocol: Http
  - name: server1
    addr: domain-to-ss-server.com # 替换成 ss 服务器的地址
    method: chacha20-ietf
    password: password
    protocol: Shadowsocks
  - name: server2
    addr: 128.113.23.12:12312
    method: chacha20-ietf
    password: password
    protocol: Shadowsocks
    obfs:  # 不设置默认不使用 obfs
      mode: Http  # 目前只支持 Http
      host: c61be5399e.microsoft.com
rules:
  - 'DOMAIN,audio-ssl.itunes.apple.com,DIRECT'
  - 'DOMAIN,gspe1-ssl.ls.apple.com,REJECT'
  - 'DOMAIN-SUFFIX,aaplimg.com,DIRECT'
  - 'DOMAIN-SUFFIX,apple.co,DIRECT'
  - 'DOMAIN-KEYWORD,bbcfmt,PROXY'
  - 'DOMAIN-KEYWORD,uk-live,PROXY'
  - 'DOMAIN-SUFFIX,snssdk.com,DIRECT'
  - 'DOMAIN-SUFFIX,toutiao.com,PROBE'
  - 'GEOIP,CN,DIRECT'  // geoip
  - 'MATCH,PROBE'
