[package]
name = "tcp_connection"
version = "0.4.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1.0.8"
async-std = "1.12.0"
nanorand = "0.7.0"
memchr = "2.5.0"
serde = { version = "1.0.140", features = ["derive"] }

[dev-dependencies]
async-std = { version = "1.12.0", features = ["attributes"] }
