[package]
name = "hermesdns"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
chrono = "0.4.13"
async-trait = "0.1.36"
tracing = "0.1.19"
tracing-futures = { version = "0.2.4", features = [
    "std-future",
], default-features = false }
async-std = { version = "1.8.0", features = ["unstable"] }
