[package]
name = "http_proxy_client"
version = "0.1.0"
authors = ["Alex.F <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.8.0"
config = { path = "../config" }
base64 = "0.13.0"
async-tls = "0.10"
parking_lot = "0.11.0"
