[package]
name = "dnsserver"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.3"
hermesdns = { path = "../hermesdns" }
config = { path = "../config" }
sled = "0.34.2"
async-trait = "0.1.36"
tracing = "0.1.19"
async-std-resolver = "0.19.5"
trust-dns-proto = { version = "0.19.5", default-features = false }

[dev-dependencies]
tempfile = "3.1.0"
