[package]
name = "dnsserver"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.11.0"
hermesdns = { path = "../hermesdns" }
config = { path = "../config" }
sled = "0.34.7"
async-trait = "0.1.53"
tracing = "0.1.34"
async-std-resolver = "0.21.2"
trust-dns-proto = { version = "0.21.2", default-features = false }

[dev-dependencies]
tempfile = "3.3.0"
