[package]
name = "dnsserver"
version = "0.5.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.12.0"
hermesdns = { path = "../hermesdns" }
config = { path = "../config" }
sled = "0.34.7"
async-trait = "0.1.57"
tracing = "0.1.36"
async-std-resolver = "0.22.0"
trust-dns-proto = { version = "0.22.0", default-features = false }

[dev-dependencies]
tempfile = "3.3.0"
