[package]
name = "config"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.115", features = ["derive", "rc"] }
url = "1.7.2"
url_serde = "0.2.0"
serde_yaml = "0.8.13"
bytes = "0.5.6"
crypto = { path = "../crypto" }
socks5_client = { path = "../socks5_client" }
smoltcp = { version = "0.6.0", default-features = false, features = [
    "proto-ipv6",
    "proto-ipv4",
    "std",
] }
