[package]
name = "ssclient"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.19"
bytes = "0.5.6"
byteorder = "1.3.4"
config = { path = "../config" }
crypto = { path = "../crypto" }
async-std = "1.6.2"
futures-util = "0.3.5"
parking_lot = "0.11.0"

[dev-dependencies]
tracing-subscriber = "0.2.11"
