[package]
name = "crypto"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.6"
rand = "0.7.3"
md-5 = "0.8.0"
digest = "0.8.1"
typenum = "1.12.0"
byte_string = "1.0.0"
byteorder = "1.3.4"
openssl = { version = "0.10.30", optional = true, features = ["vendored"] }
libc = "0.2.74"
hkdf = "0.8.0"
sha-1 = "0.8"
libsodium-sys = { version = "0.2.6", optional = true }
ring = { version = "0.16.15", optional = true }

[features]
default = ["sodium", "rc4", "aes-cfb", "aes-ctr", "camellia-cfb", "use-ring"]
sodium = ["libsodium-sys"]
rc4 = ["openssl"]
aes-cfb = ["openssl"]
aes-ctr = ["openssl"]
camellia-cfb = ["openssl"]
use-ring = ["ring"]
