[package]
name = "seeker"
version = "0.4.4"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.19"
tracing-subscriber = "0.2.11"
tracing-futures = { version = "0.2.4", features = [
    "std-future",
], default-features = false }
config = { path = "../config" }
dnsserver = { path = "../dnsserver" }
ssclient = { path = "../ssclient" }
socks5_client = { path = "../socks5_client" }
http_proxy_client = { path = "../http_proxy_client" }
sysconfig = { path = "../sysconfig" }
tun_nat = { path = "../tun_nat" }
file-rotate = { git = "https://github.com/gfreezy/file-rotate", rev = "2a7cd8b5c52c5ee17db72d80cf49b74764e97679" }
async-std = "1.8.0"
parking_lot = { version = "0.11.0", features = ["deadlock_detection"] }
async-signals = "0.3.1"
libc = "0.2.74"
futures-util = "0.3.5"
clap = "2.33.2"
async-std-resolver = "0.21.0-alpha.4"
ureq = "1.3.0"
crypto = { path = "../crypto" }
bytes = "0.5.6"
base64 = "0.12.3"
anyhow = "1.0.32"
